language: csharp
#sudo: required
sudo: false
dist: trusty # Ubuntu 14.04
mono: latest
dotnet : 2.1.403

before_install:

 - dotnet restore build.proj

install:

  # workaround for missing .net 4.5 targing pack

  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

script:
 - dotnet fake build

branches:
  except:
    - gh-pages