language: csharp
#sudo: required
sudo: false
dist: trusty # Ubuntu 14.04
mono: latest
dotnet : 2.1.403

before_install:

 - dotnet restore build.proj


script:
 - dotnet fake build

branches:
  except:
    - gh-pages